BugFix: [false positives] Increase command timeout
Without increased command timeout following error is often raised because appliance didn't respond within default command timeout (30s): ```An exception occurred during task execution. To see the full traceback, use -vvv. The error was: See the timeout setting options in the Network Debug and Troubleshooting Guide.
[...]
ansible.module_utils.connection.ConnectionError: command timeout triggered, timeout value is 30 secs.
[...]
```

Higher timeout's (because of network latency or slower appliances) should be increased by manually overwriting the default command timeout through inventory variables or environment variables.  Review plugins\connection\isam.py DOCUMENTATION section for details.